version: "3.2"

services:
  db:
    image: mariadb:10
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ${LOCAL_DB_DIR}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  redis:
    image: redis:6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always

  web:
    build: ./docker/web
    restart: always
    volumes:
      - ${LOCAL_APP_DIR}:/var/www/html:ro
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    depends_on:
      - app
      - cron
    healthcheck:
      test: "curl --fail -s http://localhost:80 || exit 1"
      interval: 30s
      timeout: 10s

  app:
    build:
      context: ./docker/app
      args:
        PUID: ${NEXTCLOUD_UID}
        PGID: ${NEXTCLOUD_GID}
        NEXTCLOUD_MAJOR_VERSION: ${NEXTCLOUD_MAJOR_VERSION:-stable}
    restart: always
    volumes:
      - ${LOCAL_APP_DIR}:/var/www/html
      - ${LOCAL_DATA_DIR}:/var/www/html/data
      - ${LOCAL_EXTERNAL_DATA_DIR}:/external
    environment:
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${VIRTUAL_HOST}
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - db
      - redis
    healthcheck:
      test: "SCRIPT_NAME=/ping SCRIPT_FILENAME=/ping REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000 || exit 1"
      interval: 10s
      timeout: 3s

  cron:
    entrypoint: /cron.sh
    build:
      context: ./docker/app
      args:
        PUID: ${NEXTCLOUD_UID}
        PGID: ${NEXTCLOUD_GID}
        NEXTCLOUD_MAJOR_VERSION: ${NEXTCLOUD_MAJOR_VERSION:-stable}
    restart: always
    volumes:
      - ${LOCAL_APP_DIR}:/var/www/html
      - ${LOCAL_DATA_DIR}:/var/www/html/data
    depends_on:
      - app
      - db
      - redis

  collabora:
    image: collabora/code:latest
    restart: always
    ports:
      - 9980
    environment:
      - "domain=${VIRTUAL_HOST}"
      - "dictionaries=en_US en_GB ja"

networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
