version: "3"

services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ${LOCAL_DB_DIR}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped

  app:
    build: ./docker/app
    restart: unless-stopped
    volumes:
      - ${LOCAL_APP_DIR}:/var/www/html
      - ${LOCAL_DATA_DIR}:/var/www/html/data
    environment:
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${LETSENCRYPT_HOST}
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - db
      - redis

  cron:
    build: ./docker/app
    restart: unless-stopped
    volumes:
      - ${LOCAL_APP_DIR}:/var/www/html
      - ${LOCAL_DATA_DIR}:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  web:
    build: ./docker/web
    restart: unless-stopped
    volumes:
      - ${LOCAL_APP_DIR}:/var/www/html:ro
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    depends_on:
      - app

networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
